"""Write MuJoCo FR3 + mocap-object wrapper XML."""
from __future__ import annotations

from pathlib import Path

_DEFAULT_FR3 = "/home/yao/franka_mujoco_sync/fr3.mujoco.urdf"

_TEMPLATE = """\
<!-- Auto-generated by twin_mujoco.prepare_fr3_scene — re-run to refresh include path. -->
<mujoco model="twin_fr3_wrapper">
  <option timestep="0.002"/>
  <include file="{fr3_path}"/>
  <worldbody>
    <geom name="floor" type="plane" size="2 2 0.05" rgba="0.8 0.8 0.8 1"/>
    <light pos="0 0 2" dir="0 0 -1" diffuse="0.9 0.9 0.9"/>
    <body name="object_cube_a" pos="0.4 0 0.05" mocap="true">
      <geom name="object_cube_a_geom" type="box" size="0.05 0.05 0.05" rgba="0.9 0.4 0.1 1"/>
    </body>
  </worldbody>
</mujoco>
"""


def write_fr3_wrapper(
    output: str | Path,
    fr3_model: str | Path = _DEFAULT_FR3,
    *,
    require_exists: bool = False,
) -> Path:
    fr3 = Path(fr3_model).expanduser()
    if require_exists and not fr3.is_file():
        raise FileNotFoundError(
            f"FR3 model not found: {fr3}. Set TWIN_MUJOCO_MODEL or pass fr3_model."
        )
    out = Path(output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_TEMPLATE.format(fr3_path=str(fr3)))
    return out
